# Generated by Django 6.0.2 on 2026-02-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_aboutpage_jobapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Article', 'Article'), ('Whitepaper', 'Whitepaper'), ('Case Study', 'Case Study'), ('Tech Report', 'Tech Report')], default='Article', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
