# Generated by Django 5.2.8 on 2026-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_category_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(default='Full-time', max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🔧', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('color', models.CharField(default='from-cyan-400 to-blue-500', max_length=100)),
                ('border_hover', models.CharField(default='hover:border-cyan-500/50', max_length=100)),
                ('glow_hover', models.CharField(default='hover:shadow-[0_0_40px_rgba(34,211,238,0.25)]', max_length=150)),
                ('accent', models.CharField(default='text-cyan-400', max_length=50)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('href', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
