# Generated by Django 5.2.8 on 2026-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobopening_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed_url',
            field=models.URLField(blank=True, help_text='If provided, this post will render as an iframe (e.g. LinkedIn embed)', max_length=500, null=True),
        ),
    ]
